import { Providers } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }): JSX.Element {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
